### ISSUE TITLE
Add favicon for the project

### ISSUE THREAD

**Issue by mateuszkornecki** [mateuszkornecki/tree-frog#47]
Right now when you open the app the only favicon you can see is the default one from the `CreateReactApp`. Change ut for something more project related -a frog emoji would be nice.

**Comment by karthickbharathi1** [comment]
Hi , @mateuszkornecki  , can you assign this issue to me?

**Comment by mateuszkornecki** [comment]
Sure! Thanks a lot, and I hope you will have fun 😺 !
